# Builds on all branches & PRs and packages for MacOS and Windows.
# Deploys to PyPi for tags.
name: Build, test and publish

on:
  push:
    branches:
      - master
      - release
      - version/*
  pull_request:
    branches-ignore:
      - l10n_master
  create:
    tags:
      - '*'

jobs:
  typechecks:
    runs-on: ubuntu-latest
    name: Type checks
    strategy:
      max-parallel: 5
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
    steps:
    - uses: actions/checkout@v3
    - uses: theCapypara/mypy-check@rust-support
      name: Run type checks
      with:
        mypy_flags: '--config-file mypy.ini'
        requirements: '-r requirements_type_checks.txt'
        python_version: '${{ matrix.python-version }}'
        
  build:
    runs-on: ubuntu-latest
    name: Build the Python wheel
    steps:
      # For tags we assume the version in setup.py is correct!
      - name: Checkout
        uses: actions/checkout@v3
      - name: Rewrite version for dev if not tag
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: |
          perl -i -pe "s/__version__\s*=\s*'(.*?)(\.rc.*|\.a.*|\.post.*)?'/__version__='\1.dev0+${GITHUB_SHA::8}'/" setup.py
      - name: Note version
        run: |
          echo "PACKAGE_VERSION=$(python3 -- ./setup.py --version)" >> $GITHUB_ENV
      - name: Build Python wheels
        uses: RalfG/python-wheels-manylinux-build@v0.5.0-manylinux2014_x86_64
        with:
          python-versions: 'cp38-cp38 cp39-cp39 cp310-cp310 cp311-cp311'
          system-packages: 'gettext'
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist/*.whl
  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    name: Deploy wheels to PyPI
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v3
        with:
          name: wheels
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          pip install twine
      - name: Publish wheels to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload *.whl
  package-windows:
    needs: build
    # Comes out of the box with:
    # - Python 3.9, incl. pip and pipx -- but we use 3.11 and install pipx ourselves.
    # - Chocolatey
    # - Visual Studio Enterprise 2022
    # - VC Redist
    # - git
    # So all we need! :))
    runs-on: windows-2022
    name: Build and package for Windows
    steps:
      # The PATH contains way too many things to start with, causing all sorts of issues with gvsbuild.
      - name: Minimize path
        run: |
          $path = "C:\pipx_bin;C:\vcpkg;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\ProgramData\Chocolatey\bin;C:\Program Files\PowerShell\7\;"
          echo "New Path:"
          echo $path
          echo $path | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"
      - name: Cache GTK-Build
        id: cache-gtk-build
        uses: actions/cache@v3
        with:
          path: "C:\\gtk-build"
          key: win-gtk-build
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install MSys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          path-type: inherit
      - name: Rewrite version for dev if not tag
        if: "!startsWith(github.ref, 'refs/tags/')"
        shell: msys2 {0}
        run: |
          perl -i -pe "s/__version__\s*=\s*'(.*?)(\.rc.*|\.a.*|\.post.*)?'/__version__='\1.dev0+${GITHUB_SHA::8}'/" setup.py
          echo "IS_DEV_BUILD=1" >> $GITHUB_ENV
      - name: Note version
        shell: msys2 {0}
        run: |
          echo "PACKAGE_VERSION=$(python -- ./setup.py --version)" >> $GITHUB_ENV
      - name: Note version
        run: |
          echo "Current Path:"
          echo $env:path
      - name: Install gvsbuild
        run: |
          # gvsbuild has issues if the pipx install path has spaces in it. It may be installed
          # in Program Files (x86) by default, so let's just make sure it isn't.
          if (Test-Path "C:\Program Files (x86)\pipx") {
              Remove-Item -path "C:\Program Files (x86)\pipx" -recurse
          }
          
          # Make sure the pipx venv dir has no spaces
          New-Item -ItemType Directory -Force -Path C:\pipx_home
          $env:PIPX_HOME = "C:\pipx_home"
          echo "PIPX_HOME=C:\pipx_home" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          New-Item -ItemType Directory -Force -Path C:\pipx_bin
          $env:PIPX_BIN_DIR = "C:\pipx_bin"
          echo "PIPX_BIN_DIR=C:\pipx_bin" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      
          python -m pip install --user pipx
          python -m pipx ensurepath
          pipx install gvsbuild
      - name: Build GTK and other libs
        run: |
          gvsbuild build --configuration release --enable-gi --py-wheel gtk3 pygobject openssl gettext gtksourceview4 hicolor-icon-theme adwaita-icon-theme
      - name: Install SkyTemple
        run: |
          
          $env:Path = "C:\gtk-build\gtk\x64\release\bin;" + $env:Path
          $env:LIB = "C:\gtk-build\gtk\x64\release\lib;" + $env:LIB
          $env:INCLUDE = "C:\gtk-build\gtk\x64\release\include;C:\gtk-build\gtk\x64\release\include\cairo;C:\gtk-build\gtk\x64\release\include\glib-2.0;C:\gtk-build\gtk\x64\release\include\gobject-introspection-1.0;C:\gtk-build\gtk\x64\release\lib\glib-2.0\include;" + $env:INCLUDE

          cd installer

          # Install themes
          curl https://skytemple.org/build_deps/Arc.zip -O
          unzip Arc.zip
          curl https://skytemple.org/build_deps/ZorinBlue.zip -O
          unzip ZorinBlue.zip

          # Install NSIS
          curl https://skytemple.org/build_deps/nsis.zip -O
          unzip -o nsis.zip -d "/c/Program Files (x86)/NSIS"

          # Install PyInstaller
          pip3 install setuptools wheel pyinstaller
          
          # Install PyGObject and pycairo
          pip install --force-reinstall (Resolve-Path C:\gtk-build\build\x64\release\pygobject\dist\PyGObject*.whl)
          pip install --force-reinstall (Resolve-Path C:\gtk-build\build\x64\release\pycairo\dist\pycairo*.whl)

          # Package
          ./build-windows.sh $PACKAGE_VERSION

          # Install latest skytemple-rust
          ./install-skytemple-rust.sh
      - name: Create installer
        uses: joncloud/makensis-action@v3.7
        with:
          script-file: "${{ matrix.arch == 'i686' && 'installer/skytemple32.nsi' || 'installer/skytemple.nsi' }}"
          arguments: "/DPRODUCT_VERSION=${{ env.PACKAGE_VERSION }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: skytemple-windows-app-${{ matrix.arch }}
          path: |
            installer/skytemple-*-install-*.exe

  package-mac:
    needs: build
    runs-on: macos-11
    name: Build and package for Mac OS
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Rewrite version for dev if not tag
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: |
          perl -i -pe "s/__version__\s*=\s*'(.*?)(\.rc.*|\.a.*|\.post.*)?'/__version__='\1.dev0+${GITHUB_SHA::8}'/" setup.py
          echo "IS_DEV_BUILD=1" >> $GITHUB_ENV
      - name: Note version
        run: |
          echo "PACKAGE_VERSION=$(python3 -- ./setup.py --version)" >> $GITHUB_ENV
      - name: Install and package
        run: |
          # git is already installed.
          brew install enchant pygobject3 gtk+3 python@3.11 gtksourceview4 adwaita-icon-theme sdl12-compat sdl2 cmake
          pip3 install -U certifi
          PATH=/usr/local/opt/python@3.11/bin:/usr/local/bin:$PATH


          # Install other dependencies and SkyTemple itself
          pip3 install py-desmume pyinstaller
          IS_MACOS=1 installer/install-skytemple-rust.sh x86_64
          pip3 install -r requirements-mac-windows.txt
          pip3 install .
          if [ -n "$IS_DEV_BUILD" ]; then
            installer/install-skytemple-components-from-git.sh
          fi

          cd installer

          # Install themes
          curl https://skytemple.org/build_deps/Arc.zip -O
          unzip Arc.zip > /dev/null
          curl https://skytemple.org/build_deps/ZorinBlue.zip -O
          unzip ZorinBlue.zip > /dev/null

          # Download armips
          curl https://skytemple.org/build_deps/mac/armips -O
          chmod +x armips

          # Package
          ./build-mac.sh $PACKAGE_VERSION

          # Creating a zip makes the artifact upload much faster since there are so many files
          zip -r skytemple-mac.zip dist/SkyTemple.app > /dev/null

      - name: Upload .app
        uses: actions/upload-artifact@v3
        with:
          name: skytemple-mac-app
          path: |
            installer/skytemple-mac.zip

      - name: Create installer
        run: |
          # See https://github.com/sindresorhus/create-dmg
          # create-dmg automatically generates an installer icon if imagemagick is installed
          brew install graphicsmagick imagemagick
          npm -g install create-dmg

          # This tool returns exit code 2 if the DMG was created but code signing failed for some reason
          npx create-dmg --dmg-title=SkyTemple installer/dist/SkyTemple.app installer || true

      - name: Upload .dmg
        uses: actions/upload-artifact@v3
        with:
          name: skytemple-mac-dmg
          path: |
            installer/SkyTemple*.dmg
